name: Vite React Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: producation  # Keeping the same name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check VITE_API_BASE_URL
        run: echo "VITE_API_BASE_URL is $VITE_API_BASE_URL"
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}  # Or vars.VITE_API_BASE_URL if using repo variable

      - name: Build Vite app
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
